# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capsule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='capsule.proto',
  package='hello_world',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rcapsule.proto\x12\x0bhello_world\"\x8f\x01\n\nCapsulePDU\x12\x1a\n\x12payload_in_transit\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\x03\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x10\n\x08prevHash\x18\x04 \x01(\x0c\x12\x0c\n\x04hash\x18\x05 \x01(\x0c\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x0f\n\x07msgType\x18\x07 \x01(\t')
)




_CAPSULEPDU = _descriptor.Descriptor(
  name='CapsulePDU',
  full_name='hello_world.CapsulePDU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_in_transit', full_name='hello_world.CapsulePDU.payload_in_transit', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='hello_world.CapsulePDU.sender', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='hello_world.CapsulePDU.signature', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prevHash', full_name='hello_world.CapsulePDU.prevHash', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='hello_world.CapsulePDU.hash', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='hello_world.CapsulePDU.timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='hello_world.CapsulePDU.msgType', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=174,
)

DESCRIPTOR.message_types_by_name['CapsulePDU'] = _CAPSULEPDU
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CapsulePDU = _reflection.GeneratedProtocolMessageType('CapsulePDU', (_message.Message,), dict(
  DESCRIPTOR = _CAPSULEPDU,
  __module__ = 'capsule_pb2'
  # @@protoc_insertion_point(class_scope:hello_world.CapsulePDU)
  ))
_sym_db.RegisterMessage(CapsulePDU)


# @@protoc_insertion_point(module_scope)
